### ISSUE TITLE
Figure out production bundling

### ISSUE THREAD

**Issue by lastmjs** [lastmjs/es-no-build#5]
The user will need a build process to bundle for production for now. Transpiling is the biggest reason, because that takes a while. If we transpile before production, that cost is gone. HTTP2 support is not at its best right now either, and so that will cause bottlenecks. Bundling solves these problems. Here's how I plan to allow it:
- Specify a simple command that the user runs based on this repo: https://github.com/systemjs/builder
- That command will find every ts entrypoint file and bundle it into a js file as a sibling of the original file
- Potentially create a custom import syntax, such as `ESNoBuild.import()` instead of System.import, so that we can control through a variable based on whether the app is in production or development, the file extension of the file to import
- Explain to the user that they can set `window.ESNoBuild.production` to true to enable importing the bundled files
- This will allow the user to dynamically determine for themselves when they are in a production environment or not

**Comment by frankwallis** [comment]
I kind of do this right now for plugin-typescript itself, I do it like this:
- compile the typescript to target 'es5', module 'es6'
- use rollup to bundle those files into a single es6 module
- use typescript again to convert that to System.register format

[rollup-plugin-typescript](https://github.com/rollup/rollup-plugin-typescript/blob/master/src/index.js) already exists but I haven't tried it, it would mean you could get rid of step (1).

**Comment by lastmjs** [comment]
I've got a good build system down using SystemJS bundler...but it still isn't ideal. Here's what I'm looking for if you have any ideas of how to get it to work. 
- No static listing of the files needed to transpile and bundle
- No changing of the client-side script imports. As in if we write `<script src="example.ts"></script>` then we don't have to change that

I'm not sure how to accomplish this, but it would be nice.

**Comment by lastmjs** [comment]
Does rollup follow your imports?

**Comment by lastmjs** [comment]
Also, @frankwallis, I've got a new project I'd like to start working on that would fix some of the limitations of `es-no-build`, SystemJS, and browser-transpilation. Imagine a development/production server that transpiles each file that is requested and stores the transpilation in memory. Then every time you request a file, the transpilation stored in memory is returned. The server will automatically watch and transpile individual files when changed.

This fixes a few problems. There is not browser transpilation, so the JS returned will be able to run immediately. The user would not ever have to explicitly specify which files would need to be transpiled, because all files requested are transpiled. The server could save to disk a list of transpiled files so that on subsequent starts it can automatically load and transpile those files. Also, the user could actually type `<script src="whatever.ts"></script>`, and wouldn't have to use any kind of alternative syntax for importing scripts.

That's probably what I'm going to start putting my efforts towards.

**Comment by lastmjs** [comment]
Here's the link to the project referenced above. No code yet, just putting ideas into the issues: https://github.com/lastmjs/zwitterion/issues/2

**Comment by lastmjs** [comment]
Update, I've begun work on Zwitterion and most everything is going exactly according to plan :)
