### ISSUE TITLE
system.js.map missing?

### ISSUE THREAD

**Issue by davidsteinberger** [lastmjs/es-no-build#6]
I've been looking for some help on how to configure _system.js_ and stumbled over your nice lib.
Exactly what I was looking for. The only issue I face is that _system.js.map_ can not be found.
It's not a big deal, but should that be included?

**Comment by lastmjs** [comment]
Hey, yes this is an issue I think I know the source of. I think it comes from the fact that I'm including the SystemJS library inline inside of config.js, and so I've left out that file. I'll need some time to get to it, but like you said I don't think it's a big issue.

**Comment by lastmjs** [comment]
Okay, fixed in the latest release.
