### ISSUE TITLE
Get rid of SystemJS dependency

### ISSUE THREAD

**Issue by lastmjs** [lastmjs/es-no-build#8]
If possible, get rid of the SystemJS dependency. We might be able to use just the es6 module loader polyfill and TypeScript. TypeSxript, if set to transpile to es5 with the system module config, should work in the browser, and modules will be loaded by the es6 module loader polyfill. We just need to figure out how to hook into the browser's script running so that we can transpile first.

**Comment by frankwallis** [comment]
Sadly AFAIK typescript won't compile commonjs -> system.register format, only es6/typescript. That is handled by this [transform](https://github.com/systemjs/babel-plugin-transform-cjs-system-wrapper/blob/master/package.json)

Another thing SystemJS provides is the resolution algorithm for plugin-typescript, which comes from all its package configuration. This needs to be handled somehow, to get from an import to its physical location. A nice simple one would be to assume imports with no file extension use the same extension as the importing file, except for non-relative paths which resolve to node_modules and use a '.js' extension. A more advanced one might need to load package.json files..

It's a really interesting idea though and something I would be happy to help with.

**Comment by lastmjs** [comment]
I suppose I'm ruling commonjs out of the scope of `es-no-build`. The goal is to be able to use es6, es7, and TypeScript, and commonjs is not part of any of those standards.

**Comment by lastmjs** [comment]
I suppose that's naive though...because we still want to support Node.js. I was only thinking about the browser, but `require` is still super important though it isn't in the ECMA standard.

**Comment by lastmjs** [comment]
@frankwallis I'm not going to be maintaining this repository anymore. I'm moving my efforts to Zwitterion, a low configuration development/production server that will support server-side transpilation, automatic file watching with live reloading, HTTP2 support, and single page application support. I've already got a working prototype up! And just like you said, I think it would be hard to get away from SystemJS and the systemjs-builder, and plugin-typescript. They are working very well for me right now, though there are some interesting hacks...one in particular...that I would love some help on.
